# 5) Você está em uma sala com três interruptores, cada um conectado a uma lâmpada em salas diferentes. Você não pode ver as lâmpadas da sala em que está, mas pode ligar e desligar os interruptores quantas vezes quiser. Seu objetivo é descobrir qual interruptor controla qual lâmpada. Como você faria para descobrir, usando apenas duas idas até uma das salas das lâmpadas, qual interruptor controla cada lâmpada?  

# # Vamos primeiramente definir as salas e os interruptores:
#     SALAS:
#     SALA 1 | SALA 2 | SALA 3

#     INTERRUPTORES:
#     INTERRUPTOR ESQUERDO | INTERRUPTOR DO MEIO | INTERRUPTOR DIREITO

# PRIMEIRAMENTE EU LIGO DOIS DOS TRÊS INTERRUPTORES, ENTÃO VAMOS SUPOR QUE EU DEIXE LIGADO O INTERRUPTOR ESQUERDO E DIRETO E O DO MEIO DESLIGADO
# EU VOU ATÉ A SALA 3 COMO POR EXEMPLO, E CASO ELA ESTIVER ESCURA, ENTÃO EU DEDUZO QUE O INTERRUPTOR DO MEIO, QUE FOI O ÚNICO DESLIGADO, É QUEM ACENDE A LAMPADA DA SALA 3
# VOLTO PARA A AREA DOS INTERRUPTORES, E AGORA EU DESLIGO OUTRO INTERRUPTOR, VAMOS DESLIGAR O INTERRUPTOR ESQUERDO E VOU ATÉ A SALA 1
# CASO A SALA 1 ESTEJA DESLIGADO, ENTÃO EU MATO QUE O INTERRUPTOR ESQUERDO ACENDE A LAMPADA DA SALA 1 
# SOBRANDO APENAS O INTERRUPTOR DIREITO LIGADO, OU SEJA, A SALA 2 ESTARA COM A LAMPADA ACESA 

# ESSA FOI A LÓGICA MAIS PRÓXIMA QUE EU PENSEI EM DESCOBRIR O QUE CADA INTERRUPTOR LIGA, PORÉM EU NÃO CONSEGUI PENSAR EM UMA MANEIRA DE O QUE FAZER, CASO EU CHEGUE NA SALA 3, E ELA ESTEJA LIGADA. NO CASO, EU ACABARIA FICANDO A MERCÊ DA SORTE. 

